version: '3.7'

services:
  kong-database:
    image: cassandra:3.11
    ports:
      - 9042:9042
  kong:
    build:
      context: .
      dockerfile: kong.Dockerfile
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    entrypoint: sh -c "./wait-for.sh kong-database:9042 && kong migrations bootstrap && ./docker-entrypoint.sh kong docker-start"

  kong-ui:
    image: pantsel/konga:latest
    ports:
      - 1337:1337
  
  product-service:
    build:
      context: .
      dockerfile: product.Dockerfile
    ports:
      - 3000:3000
    tty: true

  order-service:
    build:
      context: .
      dockerfile: order.Dockerfile
    ports:
      - 8087:8087

