sudo: false
language: node_js
node_js:
  - "stable"
services:
  - "mongodb"
cache:
  directories:
    - "node_modules"
install:
  - "npm install --no-optional"
before_script:
  - "npm info dredd version"
